Add dev_settings to enable logging to console
ThreeSixtyGiving/datastore pull request #172
Opened 2023-11-30 12:05 UTC by R2ZER0

2023-11-30 18:47 UTC, michaelwood requested changes
Looks useful! Just one minor comment.

2023-11-30 18:47 UTC, michaelwood commented on datastore/settings/settings_dev.py
> +SECRET_KEY = "itsasecret"
could we use something slightly less static like `__path__` or HOSTNAME + something or something, just for the case where we've got multiple dev instances running. Also certain bots/people probing this repo will look for strings like this and may decide to try (and fail to) and exploit it in live.

2023-12-01 16:19 UTC, R2ZER0 commented on datastore/settings/settings_dev.py
> +SECRET_KEY = "itsasecret"
In the end I've used `hostname` + `os.getcwd()` because __path__ seems to be undefined in the context of runserver :shrug:

2023-12-04 12:09 UTC, michaelwood approved these changes

2023-12-04 12:21 UTC, merged