Rg/publisher etc monitoring
ThreeSixtyGiving/datastore pull request #249
Opened 2024-12-17 11:09 UTC by R2ZER0

2025-02-18 15:10 UTC, R2ZER0 commented
Reminder: We'll also need to add the gather metrics management command to the daily `data_run.sh`

2025-02-18 18:48 UTC, michaelwood requested changes
This all looks good, only one thing I think I'd like to see change before merging which is the placement of the APIViews not being in the same module/app as their corresponding urls.

2025-02-18 18:48 UTC, michaelwood commented on datastore/monitoring/api.py
> +class SnapshotAPIView(ListAPIView):
The APIViews "belongs" in `/datastore/api/<what they export/logically do>/api.py` . This collates all the code that runs those "exporting" data out of the datastore into one place. This is an arbitrary decision but is important to stay consistent with that to avoid design fragmentation.

e.g.
```
$ git grep APIView
datastore/api/dashboard/api.py:33:class Publishers(generics.ListAPIView):
datastore/api/dashboard/api.py:53:class Publisher(generics.RetrieveAPIView):
datastore/api/dashboard/api.py:62:class Sources(generics.ListAPIView):
datastore/api/experimental/api.py:13:class CurrentLatestGrants(generics.ListAPIView):
datastore/api/org/api.py:17:class OrganisationListView(generics.ListAPIView):
datastore/api/org/api.py:35:class OrganisationDetailView(generics.RetrieveAPIView):
datastore/api/org/api.py:58:        Based on upstream DRF GenericAPIView.get_object().
datastore/api/org/api.py:103:class OrganisationGrantsMadeView(generics.ListAPIView):
datastore/api/org/api.py:134:class OrganisationGrantsReceivedView(generics.ListAPIView):
datastore/api/org/api_schema.py:1:from drf_spectacular.views import SpectacularAPIView
datastore/api/org/api_schema.py:35:class APISchemaView(SpectacularAPIView):
```

2025-02-18 18:48 UTC, michaelwood commented on datastore/monitoring/api.py
> +        # If no date is specified, use today's date
minor - comment might be redundant as you've actually implemented that below?

2025-02-18 18:48 UTC, michaelwood commented on datastore/monitoring/api.py
> +        # This is not the most efficient query, but it's only meant to be accessed occasionally, and still renders in ms
minor - A description of what it does in a comment might be good instead here!

2025-02-18 18:48 UTC, michaelwood commented on datastore/monitoring/models.py
> +    timestamp = models.DateTimeField()
I'm just wondering if there is a need to be able to group datasets/snapshots in a way that doesn't rely on datetime, how difficult would it be to remove an erroneous one later on if two were generated at the same time?

2025-02-18 18:48 UTC, michaelwood commented on datastore/data_quality/management/commands/rewrite_quality_data.py
> +            with Pool(options.get("threads") or 8) as process_pool:
minor - can drop the `or 8` as you've set a default.

2025-02-18 18:53 UTC, michaelwood commented
Great to see all the hard work on the testing. Looks like coverage indicator is looking good. https://coveralls.io/github/ThreeSixtyGiving/datastore?branch=rg/publisher-etc-monitoring

2025-02-19 09:00 UTC, michaelwood commented
One other little request is to add something to the README in the key modules section. Thanks

2025-02-24 16:55 UTC, R2ZER0 commented on datastore/monitoring/models.py
> +    timestamp = models.DateTimeField()
That is a good point, especially since snapshots timestamps are the `.datetime` of the last GetterRun, so if we created 2+ snapshots of the same GetterRun, they'd all have the same timestamp.

I guess there's the implicit Django `.id` autoincrement, do we want to make it explicit like GetterRuns?

2025-02-24 16:55 UTC, R2ZER0 commented on datastore/monitoring/api.py
> +class SnapshotAPIView(ListAPIView):
Moved it into `api/monitoring/api.py`

2025-02-25 17:54 UTC, michaelwood commented on datastore/monitoring/models.py
> +    timestamp = models.DateTimeField()
(in a meeting we discussed an additional model that groups snapshots together for convenience)

2025-03-03 21:58 UTC, michaelwood commented on requirements_dev.txt
> +    # via -r /home/rikki/Projects/datastore/requirements.in
pip-compile strike again, can you remove the full path

2025-03-03 22:08 UTC, michaelwood commented on datastore/data_quality/management/commands/rewrite_quality_data.py
> +            with Pool(options.get("threads")) as process_pool:
I think `options.threads` here? Pool can't take None and it's been initialised through through the default

2025-03-03 22:18 UTC, michaelwood commented on datastore/monitoring/models.py
> +        )
No change needed, just a thought  - Appreciate the comments here for documentation, though one thing that I've found helpful with more complicated queries is just an example of what   `latest_record_pks`  could look like (unless it's too huge to describe) so for other things I've done something like: 
```
# Generates latest_records_pk
[ 
  { "blah": "cat", "moo" : [ "Labrador" ,  "Alsatian" ] } 
  ...
]
```

I think if anyone was working on this the first thing they'd do was `print latest_record_pks`, examples I think can be worth a 1000 words!

2025-03-03 22:19 UTC, michaelwood approved these changes
Great - Approved, a couple of possible things to follow up with.

2025-03-04 13:16 UTC, merged

2025-03-04 13:19 UTC, R2ZER0 commented on datastore/monitoring/models.py
> +        )
That's a point, `latest_record_pks` is literally just a list of integer primary keys `[123, 456, 73737, ...]` of the *MetricsRecords to display, but i should make that clear. It makes more sense if you see the SQL that's generated, i can include that too